---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana
    visualize: "true"
    app: grafana
  name: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    nodePort: 30300

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
        visualize: "true"
        run: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - name: web
          containerPort: 3000