
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      name: pushgateway
      labels:
        app: pushgateway
        visualize: "true"
        run: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway
        ports:
        - name: web
          containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pushgateway
    visualize: "true"
    app: pushgateway
  name: pushgateway
spec:
  selector:
    app: pushgateway
  type: NodePort
  ports:
  - name: scrape
    protocol: TCP
    port: 9091
    nodePort: 30901
